INSERT INTO categorias (categoria_id, nombre, descripcion) VALUES
(1, 'Electrónica', 'Dispositivos electrónicos y gadgets'),
(2, 'Ropa', 'Prendas de vestir para todas las edades'),
(3, 'Alimentos', 'Comida y bebidas'),
(4, 'Hogar', 'Artículos para el hogar y decoración'),
(5, 'Juguetes', 'Juguetes y juegos para niños'),
(6, 'Deportes', 'Artículos deportivos y fitness'),
(7, 'Libros', 'Libros y material de lectura'),
(8, 'Papelería', 'Útiles escolares y de oficina'),
(9, 'Belleza', 'Productos de belleza y cuidado personal'),
(10, 'Salud', 'Productos de salud y bienestar'),
(11, 'Automotriz', 'Accesorios y refacciones para autos'),
(12, 'Mascotas', 'Productos para mascotas'),
(13, 'Jardinería', 'Herramientas y productos para jardín'),
(14, 'Electrodomésticos', 'Aparatos para el hogar'),
(15, 'Computación', 'Hardware y accesorios de cómputo'),
(16, 'Celulares', 'Teléfonos móviles y accesorios'),
(17, 'Videojuegos', 'Consolas y juegos'),
(18, 'Música', 'Instrumentos y accesorios musicales'),
(19, 'Fotografía', 'Cámaras y equipo fotográfico'),
(20, 'Relojes', 'Relojes y accesorios'),
(21, 'Zapatos', 'Calzado para todas las edades'),
(22, 'Bolsas', 'Bolsas, mochilas y maletas'),
(23, 'Joyería', 'Anillos, collares y más'),
(24, 'Ferretería', 'Herramientas y materiales'),
(25, 'Arte', 'Materiales y artículos de arte'),
(26, 'Cocina', 'Utensilios y accesorios de cocina'),
(27, 'Bebés', 'Productos para bebés'),
(28, 'Viajes', 'Accesorios y artículos de viaje'),
(29, 'Ofertas', 'Productos en promoción'),
(30, 'Otros', 'Categorías misceláneas');
